### ISSUE TITLE
Issues with !isNative

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#12]
If isNative == true, animations displayed correct.
But if isNative == false - something is wrong.

Examples:
[bonus.zip](https://github.com/rainyt/OpenFLSpine/files/3656299/bonus.zip)
[wild.zip](https://github.com/rainyt/OpenFLSpine/files/3656300/wild.zip)

Also performance of bonus animation is lower for some reasons

**Comment by CrazyFlasher** [comment]
Also in case of isNative false, animation doesn't return to the first frame, if loop is false

**Comment by rainyt** [comment]
In the case where isNative is false, most of the features are limited, such as transparency, color changes, and so on. If you want to render properly in the case of isNative=false, you should avoid this.

**Comment by CrazyFlasher** [comment]
Ok. But why it shows frames from 2 animations at one time? And doesn't return to first frame? For ex. in wild.zip. Can it be fixed?

**Comment by rainyt** [comment]
https://github.com/rainyt/OpenFLSpine/commit/7b9edce23eb69ffc61f3f895957ce7089d9e397d

Have you seen if this modification helped you?

**Comment by CrazyFlasher** [comment]
Woohooo! Looks much better now! You are the greatest :)
