### ISSUE TITLE
Update animation manually

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#13]
Is it possible to update animations manually?
I see there is hardcoded 1/60 update time. So animation playback will depend on fps.
I would like animations depend on time.
What is the better way to do that?

**Comment by rainyt** [comment]
https://github.com/rainyt/OpenFLSpine/commit/e4e61eab73d1a001f860a0be1c9c240d0732ee16
I added the process of playing the animation according to the actual time, you can update this to try.

**Comment by CrazyFlasher** [comment]
Works! Thanks!

**Comment by rainyt** [comment]
Update to 1.5.4 version.
