### ISSUE TITLE
Color transforn issue with tilemap skeleton animaion

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#16]
Hi.
Color there is another color transform issue. Can you take a look please?
![diff](https://user-images.githubusercontent.com/1607138/67368274-b5b99180-f57f-11e9-9c8a-a5046d937618.jpg)
[bonus.zip](https://github.com/rainyt/openfl-spine/files/3760764/bonus.zip)

I can send spine source if needed

**Comment by rainyt** [comment]
Is it because the color of the last object never changes?

Openfl-spine looks like a color difference, is this wrong?

**Comment by rainyt** [comment]
You can try this. https://github.com/rainyt/openfl-spine/commit/50dd851b2ad8fe0c486ef9a3a48c00b800dbbef8

**Comment by CrazyFlasher** [comment]
Hi. Still not like expected :(

Expected:
![expected](https://user-images.githubusercontent.com/1607138/67545327-61d6b600-f701-11e9-9586-7d8bf7bc3eb5.gif)

Actual:
![actual](https://user-images.githubusercontent.com/1607138/67545338-69965a80-f701-11e9-919f-a213ca3a361d.gif)

May be issue can be fixed by changing anything is source?
Link to source:
http://188.166.108.195/bonus.zip

**Comment by rainyt** [comment]
It may be that there is a problem with the color change calculation and you have to find the correct calculation method.

**Comment by rainyt** [comment]
This is a bit special, I don't know if there is a difference in the colorTransform implementation.

**Comment by CrazyFlasher** [comment]
It's interesting, that "S" char color transform animates correctly. But other letters don't

**Comment by rainyt** [comment]
It was only affected by Alpha, like it was hidden.

**Comment by rainyt** [comment]
🤔It looks like the Color value is not set correctly.

**Comment by rainyt** [comment]
I tested it. He has two layers of letters. The color of the letters below is changed normally. Should the letters above be hidden or not displayed?

**Comment by CrazyFlasher** [comment]
I guess so

**Comment by rainyt** [comment]
I think the above layer of letters can be removed, or set to alpha = 0

**Comment by CrazyFlasher** [comment]
You mean set alpha to 0 in animation or in setup settings?
It's strange, that it works OK in Spine directly and in Pixi

**Comment by rainyt** [comment]
Yes, try setting alpha=0 in the editor.

What other attributes does Spine affect the Slot object?

**Comment by rainyt** [comment]
https://github.com/rainyt/openfl-spine/commit/eb2a0d849dc0f46b9f478e63593aeffbdc2ebbef
And
https://github.com/rainyt/openfl-spine/commit/2a40997bb56c9492502f66c375b95b9b78040afb
I guess no, it has fixed this problem. 
Try try try~!

**Comment by CrazyFlasher** [comment]
MAN! YOU ARE MEGA-SUPER-COOL! IT WORKS NOW!!!!!!!!

**Comment by rainyt** [comment]
Good, haxelib update to openfl-spine1.5.5
