### ISSUE TITLE
Colors issues with openfl dev branch and tilemap skeletons

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#17]
May be it's related to OpenFL:

**OpenFL 8.9.5** - OK
![image](https://user-images.githubusercontent.com/1607138/67382592-692d8080-f596-11e9-85fc-847142a6f600.png)

**OpenFL dev branch** - WRONG
![image](https://user-images.githubusercontent.com/1607138/67382413-1bb11380-f596-11e9-9437-a2cab2ebd73e.png)

**Comment by rainyt** [comment]
It is currently recommended to use the stable version 8.9.5. The stability of the open version still needs to be tested.

**Comment by rainyt** [comment]
Confirm that Openfl9 does not have this problem
