### ISSUE TITLE
This repository unnecessarily duplicates most of spine-hx project and doesn't even mention it 

### ISSUE THREAD

**Issue by jeremyfa** [rainyt/OpenFLSpine#3]
Author or the automatic spine runtime conversion system that generates [spine-hx](https://github.com/jeremyfa/spine-hx) here.

I've run into your openfl spine renderer repository and to my surprise I noticed that you copy and pasted most of [spine-hx](https://github.com/jeremyfa/spine-hx) code to your repository without any mention to prior work.

This leads us to several problems:

- Duplicating the whole spine runtime code is unnecessary, your renderer lib could simply use spine-hx as a dependency

- Your renderer won't get future fixes of spine-hx because you duplicated it, and if you do some fixes yourself to the runtime, you are not contributing these back to spine-hx

- Developers wanting to use more recent spine-hx versions with your renderer just can't as it will conflict with your duplicated code

- Your repository is misleading the end user because you are not even mentioning where the runtime code comes from thus are somehow pretending you are the sole author of it.

For your information [spine-hx](https://github.com/jeremyfa/spine-hx) is the result of weeks of work to generate an automatically converted spine runtime for Haxe and would not exist otherwise, so the least I am asking for is to **get credits for my work instead of simply see it stolen without any mention**.

Thank you for your consideration.

**Comment by rainyt** [comment]
I am very sorry, I am negligent, I have added the source of spine-hx, thank you for your great invention. Because I made some changes to the spine-hx code to support the correct renderer now. But I believe that this problem can be solved, please wait for my subsequent version iteration. If you feel that the problem has been resolved, please help me close this question.

**Comment by jeremyfa** [comment]
Thanks.

I don't know what changes you needed to make your renderer work, but yes, ideally you should avoid modifying spine-hx code and just point to the auto-generated files of spine-hx (except for the `spine.support.*` files which are not auto-generated, so could be improved/fixed if needed).

**Comment by rainyt** [comment]
Thank you, I just went back to check the code and found that it is a problem with flipY. Now I give it a correct value and it can be displayed normally. The current spine-hx code has not changed, which means the renderer can handle it independently. Thank you for your reminder, if you can, I still hope that openfl-spine will introduce spine-hx separately to provide a stable version.

**Comment by rainyt** [comment]
Or is there any way to automatically bind your spine-hx to haxelib?

**Comment by jeremyfa** [comment]
I published spine-hx to haxelib, so you could just add it as a dependency to your own haxelib https://lib.haxe.org/p/spine-hx/
