### ISSUE TITLE
Renderer for Starling

### ISSUE THREAD

**Issue by flashup** [rainyt/OpenFLSpine#4]
Hi! Great work!
Are you going to create renderer for [openfl/starling](https://github.com/openfl/starling) library?

**Comment by rainyt** [comment]
Oh, sorry, Starling is not used in my project and I may not have time to deal with it. But I guess there is Mesh support in Starling 2.0, it should be easy to implement rendering.

**Comment by flashup** [comment]
I tried to implement it. But `spine-hx` uses java version of spine and official runtime for starling uses as3 version of spine. And they are have some differences for some reason. And I'm not sure which one is newer...

**Comment by rainyt** [comment]
You can use the hexe file generated by spine-hx, which is generally close to the latest. It has generated a version 3.6 in spine-hx.

**Comment by flashup** [comment]
Ok, thanks.
