### ISSUE TITLE
Issues, when drawing to BitmapData

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#8]
```
var bitmapData:BitmapData = new BitmapData(500, 500, true, 0x00fffff);
bitmapData.draw(stage, null, null, null, true);

var previewBitmap:Bitmap = new Bitmap(bitmapData, null, true);
stage.addChild(previewBitmap);
```
![image](https://user-images.githubusercontent.com/1607138/65129216-899c7500-da03-11e9-9134-cd97e419ed66.png)

**Comment by rainyt** [comment]
It feels like this is not a problem with spine, it is more like the problem of openfl. I rarely use draw because it is not compatible on some platforms, I need some time to look at it.

**Comment by rainyt** [comment]
Can use `@:privateAccess glBitmapData.readable = false;` to draw.
